language: php

matrix:
  include:
    - php: 7.1
    - php: 7.2

before_script:
  - composer self-update
  - composer update --prefer-source

script:
  - vendor/bin/phpunit
  - composer install --no-dev
  - composer dump-autoload --optimize --no-dev --classmap-authoritative