language: php
php:
- 7.1
- 7.2
matrix:
  includes:
  - php: 7.1
  - php: 7.2
script:
- composer self-update
- composer update --prefer-source
- vendor/bin/phpunit
jobs:
  include:
  - stage: build
    before_deploy:
    - composer install --no-dev
    - composer dump-autoload --optimize --no-dev --classmap-authoritative
    - wget https://github.com/box-project/box2/releases/download/2.7.5/box-2.7.5.phar
    - mv box-2.7.5.phar box.phar
    - php -dphar.readonly=0 box.phar build -v
    - mkdir -p behat-logger-cli
    - cp behat-logger-cli.phar behat-logger-cli/behat-logger-cli
    - set -e
    - npm version "$TRAVIS_BRANCH" || echo "set version"
    - set +e
    - cp package.json behat-logger-cli/
    - cp README.md behat-logger-cli/
    - tar -zcvf behat-logger-cli.tar.gz behat-logger-cli/
    deploy:
    - provider: releases
      api_key:
        secure: Eg0gSHDw9aEFd0SBjtEdGolqIdSg62aQTts6Ss8DNTLrzi3uRAK57ktEYL/cxHqOHFzmWsnj2bn0lIpqWb8dZlPKaJmRiKVlJQQXTHbi0muKlJ0tfm5hEzjxN04toym9gp2qzJI+Nyj0H49ikulLfQIOsWapw0NbpeyFyMEnAUDjUMiYmatVrkfUXM/GDFij6kDbCCNxLfasGTNnPiCAHlu+Y/osx2DyxY05gYBigOE3V0kTPEsgeG9hKcZkuuWNp02kWbJGmW8aidSC0DF1giKSd5hBUPvEWfnJmEBy41PwQaXp+bs8DI4Dx2wrDrBIN+VfUIdfqadNWhpLt+C815IADwiasUk9m/kCSDVBAOtLRGzj1fuOsRKECOBbq3Tq9rfQsZhl10yPh43Mg990nVvK1LY8j0YCGm1hcxxeLf718NRv83BYC6Pg/hvcOXGg4H1xiWNyeYysZmW1ZBRR2iUHDW/h7lgj/v/671XXWqiARMn0v0xflUcsCy18p44gUZumZU/A3tqN8MMLBzF6Bw8osD+AfnRCDJaAT6/naY+oKTXmIAJVrDVicTc5+eNmoa2+7tjBqBi28fR82ULi3t3SjkJw3DQGvSLdzrncCPwlt9zwsPST38gCrQsI252fTBVNuuVO0gjLWN8ZHvS5ZwlAQ6lnDnZv9nkIOEFYSj8=
      skip_cleanup: true
      file:
      - behat-logger-cli.phar
      - behat-logger-cli.tar.gz
      on:
        tags: true
        repo: Seretos/BehatLoggerExtension
#    - provider: npm
#      api_key:
#        secure: Y0H37h5zN/8io7tJLQCAf9WYldN5le8HhypLdCPnslAdmzlNWMv7A6Vgjo53JCvPHAEVyUTrf4jnJrQ8qinqDfRMvMmFsHsi/6f/GwV4qGIVbQKj4AKui0nUAlcIGpgfshd58nwwXsnzfsBuVZj6+L073R7sbX8sQVAadB+qk1pZe5SrMka9EKoPn3XNnp4OSbswzkc7Tem/3BOnA/7Wn1Gwu1oF6YB12Kj0EOkbT06U7n53jFVcgoOzFNZxjrmlKugaSMioQ1gO2E3UHjedRdFgc7l1/Og0xcB+D4BUyUD8B4rfegs+4U+pBUTdM727qPbRKxDTloVKa+4cc62RjBZ/4JIQNtHOLsbZhLj5dfj9kCocUyn7ytUC9aG91yvoBQav0PJSTJ+mA+/mcEUYZd77kav994fTu+HMl997WrJMmk4JtSaDxbwY/q93avALXSly7acULxYDHAmN/wJr7jD+JQepsoosrjVLVHibJPenmZcFdK5m/HYWK5X9FrNAftJlFRfFqFOTigiPUTn9xDZHI+c/454nS0xAdvIVwSuhGsfefl39oc4Ql5N6RzYx0yU76mS1d95ODSMz/jus5ZrfaxiUSzSbvvdyaVtc3QZglmwEksgD9L3993yrC/UDNKd3Bt595L+HgrNhMhxfBDPmBxdXWXMwVkM0P0Quv8Q=
#      skip_cleanup: true
#      on:
#        tags: true